// account
export const CREATE_MY_ACCOUNT = 'CREATE_MY_ACCOUNT';
export const ERROR_CREATE_MY_ACCOUNT = 'ERROR_CREATE_MY_ACCOUNT';
export const EDIT_MY_ACCOUNT = 'EDIT_MY_ACCOUNT';
export const ERROR_EDIT_MY_ACCOUNT = 'ERROR_EDIT_MY_ACCOUNT';
export const DELETE_MY_ACCOUNT = 'DELETE_MY_ACCOUNT';
export const ERROR_DELETE_MY_ACCOUNT = 'ERROR_DELETE_MY_ACCOUNT';

// messenger
export const INSERT_MESSAGE = 'INSERT_MESSAGE';
export const INSERT_MESSAGE_FAIL = 'INSERT_MESSAGE_FAIL';
export const INSERT_MESSAGE_SUCCESS = 'INSERT_MESSAGE_SUCCESS';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const SYNC_MESSAGE = 'SYNC_MESSAGE';

export const ADD_THREAD_LIST = 'ADD_THREAD_LIST';
export const CHANGE_CURRENT_THREAD = 'CHANGE_CURRENT_THREAD';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSENGER = 'CLEAR_MESSENGER';

// authentication
export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const PASSWORD_NOT_SAME = 'PASSWORD_NOT_SAME';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
